@startuml

State Partido {
  [*] -> Inicio
  State Reloj <<choice>>
  State Inicio
  State PeríodoIntermedio

  State Período {
    Saque --> EnJuego
    EnJuego --> Detenido
    Detenido --> Saque  
  }
  Inicio --> Saque
}

Período --> Reloj : Final de un período
Reloj --> PeríodoIntermedio : Quedan períodos
Reloj --> [*] : No quedan períodos

PeríodoIntermedio --> Inicio

@enduml
