@startuml

Partido  --> Período : Se desarrolla en un >

Alineación --> Partido : Disputa >

Equipo --> Alineación : Presenta >

Árbitro --> Partido : Dirige >

Jugador --> Equipo : Pertenece >

Partido --> Reglas : Sigue >

Persona <|-- Árbitro
Persona <|-- Jugador

@enduml
