@startuml
left to right direction

package Liga {

    package Partido {

        actor Configurador

        usecase CrearPartido
        usecase DefinirAlineacion

        Configurador --> CrearPartido
        Configurador --> DefinirAlineacion


        package Encuentro {

            actor Relator
            usecase CrearEncuentro

            Relator --> CrearEncuentro

            package Periodo {
                usecase AñadirPeriodo
                useCase AgregarOcurrencia

                Relator --> AñadirPeriodo
                Relator --> AgregarOcurrencia

            }
        }
    }

    actor Administrador    

    usecase InscribirJugador
    usecase InscribirEquipo

    usecase ListarLigas
    usecase CrearLiga

    Administrador ---> InscribirEquipo
    Administrador ---> InscribirJugador


    Administrador --> CrearLiga
    Administrador -u-> ListarLigas
    Relator -u-> ListarLigas
    Configurador -u-> ListarLigas
}

@enduml
