@startuml
left to right direction

actor Administrador
usecase InscribirJugador
usecase InscribirEquipo

Administrador ---> InscribirEquipo
Administrador ---> InscribirJugador


package Partido {

usecase CrearPartido
usecase DefinirAlineacion
Administrador --> CrearPartido
Administrador --> DefinirAlineacion


package Encuentro {

actor Relator
usecase CrearEncuentro

Relator --> CrearEncuentro

package Periodo {
usecase AñadirPeriodo
useCase AgregarOcurrencia

Relator --> AñadirPeriodo
Relator --> AgregarOcurrencia

}

}

}

@enduml
